# Generated by Django 5.1.7 on 2025-03-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=20)),
                ('recipe_discription', models.TextField()),
                ('recipe_image', models.ImageField(upload_to='recipe_photos')),
            ],
        ),
    ]
